import autoTable from "jspdf-autotable";
import { formatToIDR } from "./salaryService";
import { jsPDF } from "jspdf";
import type { Payroll } from "@/types/payroll";

// Print detailed payroll slip
export function printDetailPayroll(item: Payroll) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  // === HEADER ===
  doc.setFont("times", "normal");
  doc.setFontSize(16);
  doc.text("Employee Pay Slip", 105, 20, { align: "center" });

  doc.setFontSize(10);
  doc.text(`Period: ${item.period}`, 20, 35);
  doc.text(`Year: ${new Date(item.period).getFullYear()}`, 20, 41);
  doc.text(`Status: ${item.status.toUpperCase()}`, 20, 47);

  // === DETAIL PEGAWAI (opsional kalau ada relasi employee) ===
  if (item.employee?.full_name) {
    doc.text(`Name: ${item.employee.full_name.toUpperCase()}`, 120, 35);
  }
  doc.text(`Department: ${item.employee?.department?.name}`, 120, 41);
  if (item.employee?.position) {
    doc.text(`Position: ${item.employee.position}`, 120, 47);
  }

  // === TABEL GAJI ===
  autoTable(doc, {
    startY: 60,
    theme: "grid",
    head: [["Description", "Amount "]],
    body: [
      ["Base Salary", formatToIDR(item.salary?.base_salary as number)],
      ["Allowance (+)", formatToIDR(item.salary?.allowance as number)],
      ["Deduction (-)", formatToIDR(item.salary?.deduction as number)],
      ["Overtime Hours", `${item.overtime_hours} hour(s)`],
      ["Overtime Rate", formatToIDR(item.salary?.overtime_rate as number)],
      ["Overtime Pay", formatToIDR(item.overtime_pay as number)],
      [
        { content: "Total Salary", styles: { fontStyle: "bold", halign: "right" } },
        { content: formatToIDR(item.total_salary as number), styles: { fontStyle: "bold" } },
      ],
    ],
    headStyles: {
      font: "helvetica",
      fillColor: [41, 128, 185],
      textColor: [255, 255, 255],
      halign: "center",
    },
    styles: {
      font: "halvetica",
      fontSize: 10,
      cellPadding: 3,
    },
    bodyStyles: {
      font: "halvetica",
      valign: "middle",
    },
    alternateRowStyles: { fillColor: [245, 245, 245] },
  });

  // === FOOTER ===
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(8);
  doc.text("Generated by HRM Payroll System - Confidential", 105, pageHeight - 10, {
    align: "center",
  });

  // === SAVE PDF ===
  const fileName = `payroll-slip-${item.period}.pdf`;
  doc.save(fileName);
}
